[package]
name = "evering-ipc"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
evering = { path = "../evering" }
evering-shm = { path = "../evering-shm" }
