[package]
name = "evering-tokio"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
evering = { path = "../../evering", features = ["std"] }
tokio.workspace = true
fastrand.workspace = true
