[package]
name = "evering-shm"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[features]
default = ["nightly"]

nightly = []

std = []
unix = ["std", "dep:nix"]
windows = ["std"]

[dependencies]
allocator-api2 = "0.3.0"

spin.workspace = true
blink-alloc = { version = "0.3.1", features = ["nightly", "sync"] }
good_memory_allocator = { version = "0.1.7", features = ["allocator"] }
rlsf = "0.2.1"

memory_addr = "0.4.0"
memory_set = "0.4.0"

nix = { workspace = true, optional = true, features = ["fs", "mman"] }
