[package]
name = "evering"
license.workspace = true
authors.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
async-channel = "2.5.0"
slab = "0.4.10"
spin = { version = "0.10.0", features = ["lock_api"] }
lock_api = "0.4.13"
crossbeam-channel = "0.5"
futures = { version = "0.3", default-features = false }

[dev-dependencies]
fastrand.workspace = true
